version: '3.7'
services:
  app:
    build: .
    ports:
      - 80:3000
    volumes:
      - .:/opt/src
    links:
      - mysql_host

  mysql_host:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: labgoal
      MYSQL_DATABASE: app_development
